Update hr.json
snipcart/snipcart-l10n pull request #120
Opened 2021-03-26 07:38 UTC by WebShapedBiz

Few fixes

2021-04-07 13:30 UTC, dominic-blain requested changes
Hello there,

Thanks for taking the time to maintain this locale. There were still a few phrases missing. This can happen for a few reason, but the most probable one is that your local repository is not synced with ours.

A simple way to fix it would be to add them back manually (I commented on the missing lines) but a better way would be to [configure a remote for your fork](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork) and then [sync your fork](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork).

Hope this helps!

2021-04-07 13:30 UTC, dominic-blain commented on locales/hr.json
> -        "save_changes": "Spremi izmjene",
Please make sure you add back those phrases:

- save_changes
- back_to_orders
- change_password
- add

2021-04-07 13:30 UTC, dominic-blain commented on locales/hr.json
> -        "view_detailed_cart": "Detalji košarice"
Please make sure you add back this phrase:

- view_detailed_cart

2021-04-07 13:30 UTC, dominic-blain commented on locales/hr.json
> -        "title": "Detalji o kupcu"
Please keep "title" under "customer_details".

2021-04-07 13:30 UTC, dominic-blain commented on locales/hr.json
> -        "show_more_subscriptions": "Više %{smart_count} Pretplata |||| Više %{smart_count} Pretplata",
Please make sure you add back those phrases:

- show_more_subscriptions
- orders
- subscriptions

2021-04-07 13:30 UTC, dominic-blain commented on locales/hr.json
> -        "title": "Resetiranje lozinke",
The structure here should be kept like this (with the correct translations, of course):
  ```
"reset_password_form": {
        "title": "Reset your password",
        "password": "New password",
        "confirmation_password": "Re-enter your new password",
        "action": "Reset password"
    },
    "change_password_form": {
        "title": "Change your password",
        "current_password": "Current password",
        "password": "New password",
        "confirmation_password": "Re-enter your new password",
        "action": "Change password"
    },
```

2021-04-07 13:30 UTC, dominic-blain commented on locales/hr.json
> -        "taxes_included_in_price": "Neke stavke imaju uključen PDV.",
Please add back this phrase: taxes_included_in_price

2021-04-07 13:30 UTC, dominic-blain commented on locales/hr.json
> -        "customer_current_password_invalid": "Neispravna lozinka."
Please add back this phrase : customer_current_password_invalid

2021-04-07 14:48 UTC, WebShapedBiz commented
Thank you very much Dominic for finding the time to help me out.

I'm not an expert in GitHub PRs and I could not figure out why are some fields missing since I did make a translation.
Nevertheless, I'll try to figure out how to fix this mess I'm causing.
Cheers.
Siniša Perović
Webshaped Business OÜ
***@***.*** ***@***.***)
+385 92 1244627 (tel:+385%2092%201244627)
https://webshaped.biz

On tra. 7 2021, at 3:30 pm, dominic-blain ***@***.***> wrote:
>
>
> @dominic-blain requested changes on this pull request.
> Hello there,
> Thanks for taking the time to maintain this locale. There were still a few phrases missing. This can happen for a few reason, but the most probable one is that your local repository is not synced with ours.
> A simple way to fix it would be to add them back manually (I commented on the missing lines) but a better way would be to configure a remote for your fork (https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork) and then sync your fork (https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork).
> Hope this helps!
> In locales/hr.json (https://github.com/snipcart/snipcart-l10n/pull/120#discussion_r608643543):
>
> > "apply": "Primjena",
>
> "type_address": "Unos adrese",
>
> "use_this_address": "Koristiti ovu adresu",
>
> "back_to_store": "Povratak u trgovinu",
>
> "close_cart": "Zatvoriti košaricu",
>
> "show": "Prikazivanje",
>
> "hide": "Skrivanje",
>
> - "apply_changes": "Primjena svih izmjena",
>
> - "yes_use_it": "Da, koristiti",
>
> - "save_changes": "Spremi izmjene",
>
> Please make sure you add back those phrases:
> save_changes
> back_to_orders
>
> change_password
>
> add
>
>
> In locales/hr.json (https://github.com/snipcart/snipcart-l10n/pull/120#discussion_r608645339):
>
> > "empty": "Vaša košarica je prazna.",
>
> - "invoice_number": "Broj Ponude",
>
> - "view_detailed_cart": "Detalji košarice"
>
> Please make sure you add back this phrase:
> view_detailed_cart
> In locales/hr.json (https://github.com/snipcart/snipcart-l10n/pull/120#discussion_r608646482):
>
> > "address": "Adresa na računu",
>
> "continue_to_shipping": "Nastaviti na dostavu",
>
> "use_different_shipping_address": "Koristiti drugu adresu za dostavu"
>
> },
>
> "customer": {
>
> - "information": "Podaci o kupcu"
>
> - },
>
> - "customer_details": {
>
> - "title": "Detalji o kupcu"
>
> Please keep "title" under "customer_details".
> In locales/hr.json (https://github.com/snipcart/snipcart-l10n/pull/120#discussion_r608646839):
>
> > "sign_out": "Odjava",
>
> - "show_more_orders": "Više %{smart_count} Narudžbi |||| Više %{smart_count} Narudžbi",
>
> - "show_more_subscriptions": "Više %{smart_count} Pretplata |||| Više %{smart_count} Pretplata",
>
> Please make sure you add back those phrases:
> show_more_subscriptions
> orders
>
> subscriptions
>
>
> In locales/hr.json (https://github.com/snipcart/snipcart-l10n/pull/120#discussion_r608648542):
>
> > @@ -117,17 +106,10 @@
>
> "action": "Poslati email poruku za ponovno postavljanje lozinke"
>
> },
>
> "reset_password_form": {
>
> - "title": "Resetiranje lozinke",
>
> The structure here should be kept like this (with the correct translations, of course):
> "reset_password_form": {
>
> "title": "Reset your password",
>
> "password": "New password",
>
> "confirmation_password": "Re-enter your new password",
>
> "action": "Reset password"
>
> },
>
> "change_password_form": {
>
> "title": "Change your password",
>
> "current_password": "Current password",
>
> "password": "New password",
>
> "confirmation_password": "Re-enter your new password",
>
> "action": "Change password"
>
> },
>
> In locales/hr.json (https://github.com/snipcart/snipcart-l10n/pull/120#discussion_r608648955):
> > }
>
> },
>
> "discounts": {
>
> "title": "Popusti"
>
> },
>
> "cart_summary": {
>
> "taxes": "PDV",
>
> - "taxes_included_in_price": "Neke stavke imaju uključen PDV.",
>
> Please add back this phrase: taxes_included_in_price
> In locales/hr.json (https://github.com/snipcart/snipcart-l10n/pull/120#discussion_r608649350):
>
> > @@ -285,22 +266,21 @@
>
> "description": "Nije bilo moguće autorizirati vaše plaćanje. Molimo pokušajte kasnije."
>
> }
>
> },
>
> - "customer_exists": "Ova se email adresa već koristi.",
>
> - "customer_password_missmatch": "Obje lozinke moraju biti jednake.",
>
> - "customer_password_token_expired": "Token za resetiranje lozinke je istekao.",
>
> - "customer_password_token_invalid": "Token za resetiranje lozinke nije valjan.",
>
> - "customer_not_found": "Email adresa nije registrirana u sustavu.",
>
> - "invalid_credentials": "Neispravna email adresa ili lozinka.",
>
> - "customer_current_password_invalid": "Neispravna lozinka."
>
> Please add back this phrase : customer_current_password_invalid
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub (https://github.com/snipcart/snipcart-l10n/pull/120#pullrequestreview-629992698), or unsubscribe (https://github.com/notifications/unsubscribe-auth/ABTTUULU5LL6TMW5SBTAQVTTHRM77ANCNFSM4Z237IJQ).
>

2021-04-07 15:03 UTC, WebShapedBiz commented
I've made all required changes and click "Commit changes". I hope that this time it will work.

Thank you again for your time and effort.

Cheers.

2021-04-14 12:39 UTC, dominic-blain commented
Hey there!

It's my pleasure :) It seems however that nothing has changed since last time. After clicking "Commit changes", you need to "Push" those change to this branch. This will send your _local_ changes to your _remote_ repository.

![image](https://user-images.githubusercontent.com/1465878/114711269-c2deb900-9cfc-11eb-8d2f-d0a0d5a09c8d.png)

Hope this helps! We are almost there :)

2021-04-14 12:53 UTC, WebShapedBiz commented
Thank you for your time and effort but I'm completely lost now. I did everything you said I should do in your last post and at the end I've made a push.
1. I cannot understand why my first PR didn't have all translation included. My local file, from which I've copied everything was at the end of that first PR a different file from the pushed GitHub version. How is that possible?
2. The same goes for the second PR.
3. I can see that there are two PRs waiting with green checks. What are those if I didn't push anything? Where did my changes go? 
![Slika zaslona 2021-04-14 14 45 12](https://user-images.githubusercontent.com/6765137/114712300-3c43cf00-9d30-11eb-9220-3d1985174380.jpeg)

Sorry for this and thank you again for your time and effort @dominic-blain, I won't be bothering you anymore. If there is really nothing changed in those two PR's then I'm declaring myself stupid and giving up this hell I don't understand.

Cheers.

2021-04-15 13:15 UTC, dominic-blain commented
After comparing both PR, it looks like the PR #108 is the most up-to-date and contains all your fixes. #108 is based on your **master** branch, while this one (#120) is based on your branch **patch-2**. It is hard to know exactly what happened on your side but this may be the reason why this PR got out of sync.

I will close this PR and merge the other one. Feel free to create new PRs based on your master branch. It should be simpler to update and keep in sync this way!

Have a nice one!

2021-04-15 13:15 UTC, closed without merging